# Generated by Django 4.1.5 on 2023-01-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('pais', models.CharField(max_length=200)),
            ],
        ),
    ]
